# Use postgres/example user/password credentials

services:
  django:
    container_name: django-tms
    image: django:task-management-system
    build:
      context: ./django_backend
      dockerfile: Dockerfile
    env_file: .env.sample
    networks:
      - task-management-system
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: postgres:17.6
    container_name: psql-tms
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    # env_file: .env.sample
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - task-management-system
    volumes:
      - dbv:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

networks:
  task-management-system: {}

volumes:
  dbv:
