# Use postgres/example user/password credentials

name: task-management-system

services:
  cache:
    image: redis:8.2.1-alpine
    restart: always
    container_name: redis-tms
    networks:
      - tms
  #############################################################################################
  # ___Option to conect throught this port from host machine___
  # port:
  #   - "6379:6379"
  #############################################################################################
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 5s
      retries: 5
  
  db:
    image: postgres:17.6
    container_name: psql-tms
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - tms
    volumes:
      - dbv:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
  #############################################################################################
  # ___Option to conect throught this port from host machine___    
  # port:
  #   - "5432:5432"
  #############################################################################################

  django:
    container_name: django-tms
    image: tms-base
    build:
      context: ./django_backend
      dockerfile: Dockerfile
    env_file: .env.sample
    networks:
      - tms
    ports:
      - "8000:8000"
  #################################################################################################
  # ___Option to create a bind mount to modify Django container files from the host.
  #   the container will reload automatically to intengrate any change.___
  #  volumes:
  #    - ./django_backend:/app
  #################################################################################################
    depends_on:
      db:
        condition: service_healthy
        restart: true
      cache:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD-SHELL", "python manage.py check --deploy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  celery:
    container_name: celery-tms
    image: tms-base
    build:
      context: ./django_backend
      dockerfile: Dockerfile
    command: celery --app=config worker -l INFO
    env_file: .env.sample
    networks:
      - tms
    depends_on:
      db:
        condition: service_healthy
        restart: true
      cache:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD-SHELL", "celery -A config inspect ping -t 5 2>/dev/null | grep -q pong"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mailhog:
    container_name: fake_email
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - tms

networks:
  tms: {}

volumes:
  dbv:
  cache:
