# Generated by Django 4.2.3 on 2025-09-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('IT', 'IT'), ('FI', 'Finances'), ('SA', 'Sales')]),
        ),
    ]
