# Generated by Django 4.2.3 on 2025-09-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='metadata',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
