# Generated by Django 4.2.3 on 2025-09-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
