FROM	python:3.11-slim

ENV		PYTHONDONTWRITEBYTECODE=1 \
	PYTHONUNBUFFERED=1
WORKDIR /app
COPY	--chmod=755 . /app/
RUN		pip install --upgrade pip && pip install -r requirements.txt
EXPOSE	8000
CMD ["bash", "/app/scripts/entrypoint.sh"]

